### ISSUE TITLE
Keeping memory of target ip (like in prev version)

### ISSUE THREAD

**Issue by bangxiangyong** [Met4FoF/datareceiver#2]
The newer version needs to have its ip add target to be tweaked again everytime i disconnect the power (without battery). I think the board needs the C2303 battery to maintain its memory, but the previous version seems to be more convenient when it finds 192.168.0.200 after a while being powered up  - even without battery. 

But you could keep the `tweaked` ip add and configuration in EEPROM or some tiny persistent storage i guess? 

I think it will be good to maintain that kind of convenience.

**Comment by BeSeeTek** [comment]
There is no eeprom but battery backuped SRAM on the STM32F767. The Data in the Backupram can be ratained over years with an single battery.

On the old version ```192.168.0.200``` was hard coded this will be no option.

the reason why you are exrpicing this problem is that the SRAM is corrupted in unpowered stad an the memeory contend becomes undefined but not 0x00000000.

If you have an look in 
https://github.com/Met4FoF/Met4FoF-SmartUpUnit/blob/SSU_V2/Src/freertos.cpp
```c++
uint32_t StartCount = configMan.getStartcount();
	SEGGER_RTT_printf(0, "StartCount is= %llu", StartCount);
	struct netconn *conn;
	struct netbuf *buf;
	//TODO REMOVE THIS AND INTEGRATE IT in web interface
	configMan.setUDPPort(7654);
	ip_addr_t targetipaddr;
	ip_addr_t settargetipaddr=configMan.getUDPTargetIP();
	if(settargetipaddr.addr==0x00000000)
		{

		uint8_t UDP_TARGET_IP_ADDRESS[4] = { 192, 168, 0, 200 };
		IP4_ADDR(&targetipaddr, UDP_TARGET_IP_ADDRESS[0], UDP_TARGET_IP_ADDRESS[1],
				UDP_TARGET_IP_ADDRESS[2], UDP_TARGET_IP_ADDRESS[3]);
		configMan.setUDPTargetIP(targetipaddr);
		}

	targetipaddr=configMan.getUDPTargetIP();
	/* create a new connection */
	conn = netconn_new(NETCONN_UDP);
```

you can see the that the board checks if the memory is empty an if yes uses ```192.168.0.200``` as traget adress.

To reset the memory hold BT1 pressed during start up

**Comment by bangxiangyong** [comment]
Yes, i think as long as battery is provided for all boards (unlike mine before), then it will be okay and convenient. 

Since otherwise, it will not retain the ip address configuration after losing power.

**Comment by BeSeeTek** [comment]
For all new boards i optained batterys ;)

**Comment by bangxiangyong** [comment]
Fantastic
